#pragma once

#include "driver/gpio.h"
#include <stdbool.h>
#include <stdint.h>

#define AQUABOX_VERSION "0.1.0"
#define AQUABOX_CHANNEL_COUNT 3
#define AQUABOX_CONTROL_PERIOD_MS 100
#define AQUABOX_PREOPEN_MS 1000
#define AQUABOX_PUMP_OFF_DELAY_MS 1000
#define AQUABOX_FLOW_START_TIMEOUT_MS 5000
#define AQUABOX_FLOW_RUNNING_TIMEOUT_MS 3000
#define AQUABOX_DEFAULT_FILL_TIMEOUT_MS (10 * 60 * 1000)

#define AQUABOX_PIN_FLOW GPIO_NUM_14
#define AQUABOX_PIN_PUMP GPIO_NUM_16
#define AQUABOX_PIN_SOL1 GPIO_NUM_17
#define AQUABOX_PIN_SOL2 GPIO_NUM_18
#define AQUABOX_PIN_SOL3 GPIO_NUM_21
#define AQUABOX_PIN_S1_LOW GPIO_NUM_39
#define AQUABOX_PIN_S1_HIGH GPIO_NUM_40
#define AQUABOX_PIN_S2_LOW GPIO_NUM_41
#define AQUABOX_PIN_S2_HIGH GPIO_NUM_42
#define AQUABOX_PIN_S3_LOW GPIO_NUM_43
#define AQUABOX_PIN_S3_HIGH GPIO_NUM_44
#define AQUABOX_PIN_PUMP_SWITCH GPIO_NUM_38
#define AQUABOX_PIN_MANUAL_SWITCH GPIO_NUM_47

#define AQUABOX_PIN_BTN_UP GPIO_NUM_4
#define AQUABOX_PIN_BTN_DOWN GPIO_NUM_5
#define AQUABOX_PIN_BTN_ENTER GPIO_NUM_6
#define AQUABOX_PIN_BTN_BACK GPIO_NUM_15

#define AQUABOX_PIN_TFT_DC GPIO_NUM_8
#define AQUABOX_PIN_TFT_CS GPIO_NUM_9
#define AQUABOX_PIN_TFT_RST GPIO_NUM_10
#define AQUABOX_PIN_TFT_MOSI GPIO_NUM_11
#define AQUABOX_PIN_TFT_SCLK GPIO_NUM_12
/* Paisagem: 160 colunas por 128 linhas. */
#define AQUABOX_TFT_WIDTH 160
#define AQUABOX_TFT_HEIGHT 128
#define AQUABOX_TFT_SPI_CLOCK_HZ (20 * 1000 * 1000)

typedef enum {
  AQUABOX_CHANNEL_DISABLED,
  AQUABOX_CHANNEL_TANK,
  AQUABOX_CHANNEL_IRRIGATION
} aquabox_channel_mode_t;
typedef enum {
  AQUABOX_ALARM_NO_FLOW = 1U << 0,
  AQUABOX_ALARM_FILL_TIMEOUT = 1U << 1,
  AQUABOX_ALARM_LEVEL_INCONSISTENT = 1U << 2,
  AQUABOX_ALARM_RTC_INVALID = 1U << 3,
  AQUABOX_ALARM_CONFIG_INVALID = 1U << 4
} aquabox_alarm_t;
typedef struct {
  bool enabled;
  aquabox_channel_mode_t mode;
  uint32_t max_fill_ms;
} aquabox_channel_config_t;
